In [2]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.optimize as opt
import scipy.linalg as la

### Compute the matrix of elasticities for your projection matrix.

In [3]:
A = 50  # Maximum age
f = 0.24  # Fecundity for ages >= 3
survival_to_age3 = 0.0722  # Survival to age 3
p_adult = 0.942  # Survival for ages 3 to 49

P = np.zeros((A + 1, A + 1))
P[0, 3:] = f 

P[1, 0] = survival_to_age3 
P[2, 1] = 1   
P[3, 2] = 1  

for a in range(3, A):
    P[a + 1, a] = p_adult

print(P)

[[0.     0.     0.     ... 0.24   0.24   0.24  ]
 [0.0722 0.     0.     ... 0.     0.     0.    ]
 [0.     1.     0.     ... 0.     0.     0.    ]
 ...
 [0.     0.     0.     ... 0.     0.     0.    ]
 [0.     0.     0.     ... 0.942  0.     0.    ]
 [0.     0.     0.     ... 0.     0.942  0.    ]]


In [4]:
eigenvalues, eigenvectors = np.linalg.eig(P)

lambda_long_term = max(eigenvalues.real)
print(f"Long-term population growth rate (λ): {lambda_long_term:.4f}")

Long-term population growth rate (λ): 0.9439


In [5]:
l,v = la.eig(P)

idx=np.argsort(np.abs(l))
l_sorted=l[idx]  
v_sorted=v[:,idx]   #rearrange eigenvectors in same order
lambda_max= l_sorted[-1]
v_max = v_sorted[:,-1]

l,v_left = la.eig(np.transpose(P))

idx=np.argsort(np.abs(l))
l_sorted=l[idx]  
v_left_sorted=v_left[:,idx]   #rearrange eigenvectors in same order
v_left_max = v_left_sorted[:,-1]

s = np.outer(v_left_max,v_max)/np.dot(v_left_max,v_max)
e= s * P / lambda_max
matrix_e = np.real(e)

In [6]:
print('Sensitivity Matrix')
print(np.real(s))  #that real is just to nicely format the output here

Sensitivity Matrix
[[0.03687976 0.002821   0.00298869 ... 0.00289309 0.0028873  0.00288151]
 [0.48213968 0.03687976 0.03907205 ... 0.03782224 0.03774646 0.03767083]
 [0.45508741 0.03481048 0.03687976 ... 0.03570008 0.03562855 0.03555717]
 ...
 [0.02807555 0.00214755 0.00227521 ... 0.00220243 0.00219802 0.00219362]
 [0.01873579 0.00143314 0.00151833 ... 0.00146976 0.00146682 0.00146388]
 [0.00937729 0.00071729 0.00075992 ... 0.00073562 0.00073414 0.00073267]]


In [7]:
print('Elasticities Matrix')

np.set_printoptions(precision=6, suppress=True)
print(matrix_e)

Elasticities Matrix
[[0.       0.       0.       ... 0.000736 0.000734 0.000733]
 [0.03688  0.       0.       ... 0.       0.       0.      ]
 [0.       0.03688  0.       ... 0.       0.       0.      ]
 ...
 [0.       0.       0.       ... 0.       0.       0.      ]
 [0.       0.       0.       ... 0.001467 0.       0.      ]
 [0.       0.       0.       ... 0.       0.000733 0.      ]]


1. Is the elasticity for fecundity values fa the same for all ages a? 
2. Is the elasticity for annual survival probabilities values pa the same for all ages a? 
3. State one possible implication for management plans.

fecundity stays the same from 0-3
the surivval probabilities are the ones that are going down clearly 
first row is all the fecundities 


1. The fecundity values are not all the same for all ages a (above age 3, the lower-limit for reproductive age). This is because the number of owls in older age groups are fewer than in lower age groups, and a higher fecundity for a younger age has a much larger overal population affect than any assigned fecundity for a smaller population
2. The elasticity for annual survival probabilities is essentially a measure of the relative contribution of that aged-animal on the overall composition of the growth rate– younger populations have a higher elasticity for the annual survival probailities because younger animals are more likeley to be alive and reproducing for a longer amount of time.
3. One possible implication for management plans to increase population growth is through focusing on increasing survival probabilities for older populations. As long as they are able to survive, they will be able to contribute towards the population growth at almost the same relative contribution as a younger animal, and the increased surival probabilities over time will trickle down to result in larger younger populations. 