In [1]:
import matplotlib.pylab as plt   # That gives plotting, and the next line makes plots appear inline in notebook
%matplotlib inline  

import numpy as np  # That gives numerical arrays and tools for manipulating them

import scipy.optimize as opt
import scipy.linalg as la

##  non positive projection matrix

In [2]:
A=np.array([
    [ 0,    0,     0,     0,    127,       4,   80],  
 [.6747,  .737,   0,     0,     0,         0,    0], 
 [   0 , .0486 , .661,    0,     0,         0,    0],  
 [   0 ,    0 , .0147 ,  .6907 ,  0 ,     0  ,  0 ],
 [   0 ,    0 ,   0   , .0518 ,    0 ,     0  ,  0 ],
 [   0 ,    0 ,   0  ,   0  ,  .8091   ,   0  ,  0 ] ,
 [   0 ,    0  ,  0  ,   0  ,   0    ,   .8091 , .8089  ]])

print(A)


[[0.000e+00 0.000e+00 0.000e+00 0.000e+00 1.270e+02 4.000e+00 8.000e+01]
 [6.747e-01 7.370e-01 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 4.860e-02 6.610e-01 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 1.470e-02 6.907e-01 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 5.180e-02 0.000e+00 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 8.091e-01 0.000e+00 0.000e+00]
 [0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 8.091e-01 8.089e-01]]


Flexible syntax within numpy, so can compute any matrix power

In [11]:
# TAKE MATRIX TO POWER SPECIFIED IN CLASS, AND CHECK POWER POSITIVITY

C= np.linalg.matrix_power(A, 6)
### TO FILL IN -- use np.linalg.matrix_power ### 
print(C)



[[6.70409974e-03 1.58645167e-02 2.09013004e-01 6.13743182e+00
  2.81218038e+01 2.77249176e+01 2.79590643e+01]
 [1.48845574e-01 1.69293677e-01 2.20242581e-01 1.07319395e+01
  8.95330897e+01 8.16416762e+01 9.67501359e+01]
 [3.93718563e-02 4.92940446e-02 9.22083398e-02 7.28148942e-01
  9.65147172e+00 7.08281449e+00 1.04956599e+01]
 [1.62924510e-03 2.52569420e-03 1.25037616e-02 1.17471042e-01
  2.06636862e-01 9.60160509e-02 2.02593844e-01]
 [7.26564113e-05 1.25085069e-04 7.95128883e-04 8.30711973e-03
  6.70409974e-03 1.82477470e-03 5.78791966e-03]
 [4.21961028e-05 8.71295425e-05 7.61149315e-04 9.53871307e-03
  2.56566527e-03 8.08083551e-05 1.61616710e-03]
 [1.63455100e-05 7.01982360e-05 1.55439848e-03 5.75334317e-02
  2.80274602e-01 2.80205321e-01 2.80136058e-01]]


Based on this we expect will have a single, real positive dominant eigenvalue, and that's what we find

In [12]:
# Compute eigenvalues
l,v = la.eig(A)

#sort eigenvalues
idx=np.argsort(np.abs(l))
l_sorted=l[idx]  

print(np.abs(l_sorted))


[0.14875044 0.14875044 0.26545281 0.37166677 0.77599166 0.77599166
 0.94503098]
